version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1-1.22-bullseye
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity